before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: linux
    goarch: arm64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  files:
  - none*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next+commit.{{ .ShortCommit }}"
release:
  draft: true
brews:
  - tap:
      owner: thestormforge
      name: homebrew-tap
    commit_author:
      name: Butch Masters
      email: butch@stormforge.io
    folder: Formula
    homepage: "https://github.com/thestormforge/konjure/"
    description: Manifest appear!
