before:
  hooks: ['go mod tidy', 'go generate ./...']
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: linux
    goarch: arm64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  files:
  - none*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next+commit.{{ .ShortCommit }}"
release:
  draft: true
  prerelease: auto
brews:
- repository:
    owner: thestormforge
    name: homebrew-tap
  commit_author:
    name: Butch Masters
    email: butch@stormforge.io
  directory: Formula
  homepage: "https://github.com/thestormforge/konjure/"
  description: Manifest appear!
  install: |
    bin.install "konjure"

    # generate and install bash completion
    output = Utils.safe_popen_read("#{bin}/konjure", "completion", "bash")
    (bash_completion/"konjure").write output

    # generate and install zsh completion
    output = Utils.safe_popen_read("#{bin}/konjure", "completion", "zsh")
    (zsh_completion/"_konjure").write output
