name: Main
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Verify
        run: |
          go mod tidy
          go generate ./...
          go fmt ./...
          go test ./...

          goreleaserFlags=()
          goreleaserFlags+=(--release-notes ./.github/RELEASE_TEMPLATE.md)
          if [ "${GITHUB_REF_TYPE}" != "tag" ]; then
            goreleaserFlags+=(--snapshot)
          fi
          echo "GORELEASER_FLAGS=${goreleaserFlags[@]}" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: v2
          args: release ${{ env.GORELEASER_FLAGS }}
        env:
          GITHUB_TOKEN: ${{ secrets.BMASTERS_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-archives
          path: dist/*.tar.gz
